### ISSUE TITLE
Add option to set up the name for the headers on config

### ISSUE THREAD

**Issue by pragmaticivan** [beam-community/scrivener_headers#7]
Instead of predefine the name of the headers, some APIs need to respect some patterns, such as `x-total, x-per-page`.

The ideal scenario would be having the current ones as default and add the possibility to use custom names as config.

**Comment by doomspork** [comment]
@pragmaticivan this is a great idea!  Would you like to take a whack at implementing it?

**Comment by pragmaticivan** [comment]
Yep, I will try it later, thanks :D

**Comment by Sardoan** [comment]
I would also suggest to change the link structure. Now it is a string with '<http...>; rel="first", <http...>; rel="next"....' I am reading the headers in an web application and parsing the link with RegExp seems strange. Json would be much nicer. link: { "first": "http...", "last": "http.."}
Don't see the point putting it all into a string. I don't know if json is allowed in headers (due to a RFC or spec), but would be nicer.  Think a switch would be cool, like page_size -> format: "standard" or "json". Has pragmaticivan  already provide an implementiation for the config?

**Comment by Sardoan** [comment]
I am relativ new to elixir, c, csharp, java and stuff, elixir is my first functional language, but check my fork. Added link as json and made the header parameter names configurable. No idea, if this was the correct way, since I am still programming oop with elixir. Any improvements are welcome. Next step would be the switch "json" or "standard" for the link.

**Comment by doomspork** [comment]
@Sardoan we don't use JSON because this package implements RFC 5988 which outlaws how we format the links.  If you're interested in reading more about the spec: https://tools.ietf.org/html/rfc5988

I'll take a peek at your fork this week 👍

**Comment by erickgnavar** [comment]
Hi there, I implemented this feature in #8
